#! /bin/zsh

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
eval "$(mise activate zsh)"

# vim keybind
bindkey -v
bindkey -M viins '^[[91;5u' vi-cmd-mode
export EDITOR='nvim'
setopt no_beep
setopt autocd
# usage: cd -<TAB>
DIRSTACKSIZE=100
setopt auto_pushd
setopt pushd_ignore_dups

# zinit download & run
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"
unalias zi

# zinit plugins
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting
zinit light Aloxaf/fzf-tab
zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode

# zsh-vi-mode conf https://github.com/jeffreytse/zsh-vi-mode
ZVM_SYSTEM_CLIPBOARD_ENABLED=true
ZVM_OPEN_FILE_CMD='nvim'
ZVM_VI_INSERT_ESCAPE_BINDKEY='^[[91;5u'

# ch pwd
function chpwd() { ls -G; }

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias -s md=glow
alias -s py=python
alias -s {json,log}='bat'
alias -s {png,jpg}='chafa --format=kitty'
alias ...=../..
alias ....=../../..
alias .....=../../../..
alias ......=../../../../..
alias _=sudo
alias ls='ls -G'
alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -lh'
alias lsa='ls -lah'
alias glow='glow --pager'
alias md='f() { mkdir -p "$1" && cd "$1"; }; f'
alias chafa='chafa --format=kitty'
ENV_DIR="$HOME/.venv/"
for envs in $(ls $ENV_DIR); do
  alias "$envs=source $ENV_DIR/$envs/bin/activate"
done

# Set up fzf key bindings and fuzzy completion
# https://github.com/junegunn/fzf
FZF_CTRL_T_OPTS="--style full --preview 'fzf-preview.sh {}' --bind 'focus:transform-header:file --brief {}'"
source <(fzf --zsh)

bindkey -M emacs -r '^T'
bindkey -M vicmd -r '^T'
bindkey -M viins -r '^T'
bindkey -M emacs '\ef' fzf-file-widget
bindkey -M vicmd '\ef' fzf-file-widget
bindkey -M viins '\ef' fzf-file-widget
bindkey -M emacs -r '^R'
bindkey -M vicmd -r '^R'
bindkey -M viins -r '^R'
bindkey -M emacs '\er' fzf-history-widget
bindkey -M vicmd '\er' fzf-history-widget
bindkey -M viins '\er' fzf-history-widget

# https://zoxide.org/ja/tutorials/
# zoxideとfzfの統合: https://zoxide.org/ja/tutorials/fzf-integration/
eval "$(zoxide init zsh)"
oil() {
  local dir
  dir=$(zoxide query -l $@ | fzf --preview 'tree -C -L 2 {}')
  [ -n "$dir" ] && z "$dir" && nvim -c "Oil"
}
zfp() {
  local dir
  dir=$(zoxide query -l | fzf --style full --preview 'tree -C -L 2 {}')
  [ -n "$dir" ] && z "$dir" && ls -la
}
zle -N zfp
bindkey -M emacs '\ec' zfp
bindkey -M vicmd '\ec' zfp
bindkey -M viins '\ec' zfp

# brew shell completion configuration
if (($+commands[brew])); then
  eval "$(brew shellenv)"
fi
#The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=($HOME/.docker/completions $fpath)
fpath=($HOME/.zsh/completion $fpath)

autoload -Uz compinit
compinit
eval "$(mise complete zsh)"
# End of Docker CLI completions
# TODO: APIキーをsecurityコマンドで取り出すようにする
# TODO: OS依存するから解決する
export GEMINI_API_KEY=

eval "$(starship init zsh)"
