[tools]
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:lazygit" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:peteretelej/tree" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:shfmt" = "latest"
"aqua:starship/starship" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"aqua:tmux" = "latest"
"github:tectonic-typesetting/tectonic" = "latest"
node = "latest"
python = "latest"
rust = "latest"
usage = "latest"
